[[local|localrc]]
ADMIN_PASSWORD=secret
DATABASE_PASSWORD=$ADMIN_PASSWORD
RABBIT_PASSWORD=$ADMIN_PASSWORD
SERVICE_PASSWORD=$ADMIN_PASSWORD
SERVICE_TOKEN=$ADMIN_PASSWORD
MYSQL_PASSWORD=$ADMIN_PASSWORD
RECLONE=yes

CINDER_REPO=https://review.opendev.org/openstack/cinder
CINDER_BRANCH=refs/changes/72/986072/7

NOVA_REPO=https://review.opendev.org/openstack/nova
NOVA_BRANCH=refs/changes/71/986071/5

LIBS_FROM_GIT=os-brick
OS_BRICK_REPO=https://review.opendev.org/openstack/os-brick
OS_BRICK_BRANCH=refs/changes/70/986070/2

# Enable Neutron
IP_VERSION=4
HOST_IP=10.221.89.60

# Disable security groups entirely
#Q_USE_SECGROUP=False
LIBVIRT_FIREWALL_DRIVER=nova.virt.firewall.NoopFirewallDriver
CINDER_SECURE_DELETE=False

# These options define  expected driver capabilities
TEMPEST_VOLUME_DRIVER=infoscale
TEMPEST_VOLUME_VENDOR="InfoScale"
TEMPEST_STORAGE_PROTOCOL=infoscale
TEMPEST_VOLUME_MANAGE_SNAPSHOT=false
TEMPEST_VOLUME_MANAGE_VOLUME=false
ATTACH_ENCRYPTED_VOLUME_AVAILABLE=false

[[post-config|$CINDER_CONF]]
[DEFAULT]
default_volume_type = infoscale-sgclass0
storage_availability_zone = openstack
enabled_backends = infoscale-1
log_dir = /opt/stack/logs
log_color = False
logging_exception_prefix = ERROR %(name)s %(instance)s
logging_default_format_string = %(levelname)s %(name)s [-] %(instance)s%(message)s
logging_context_format_string = %(levelname)s %(name)s [%(global_request_id)s %(request_id)s %(project_name)s %(user_name)s] %(instance)s%(message)s
logging_debug_format_suffix = {{(pid=%(process)d) %(funcName)s %(pathname)s:%(lineno)d}}

[infoscale-1]
volume_driver = cinder.volume.drivers.infoscale.InfoScaleCinderDriver
inf_base = /cinderhost
backend_availability_zone = openstack
volume_backend_name = infoscale
inf_rest_ip = rest.infoscale-cinderaz1
inf_rest = /infoscale/api/2.0
inf_port = 5636
inf_restcert = /opt/stack/cinder-cert/cinder.crt
inf_restkey = /opt/stack/cinder-cert/cinder.key
inf_export = True
inf_ssl_verify = False

[[post-config|$NOVA_CONF]]
[DEFAULT]
log_dir = /opt/stack/logs
log_file = nova-schedular.log
log_color = False
logging_exception_prefix = ERROR %(name)s %(instance)s
logging_default_format_string = %(levelname)s %(name)s [-] %(instance)s%(message)s
logging_context_format_string = %(levelname)s %(name)s [%(global_request_id)s %(request_id)s %(project_name)s %(user_name)s] %(instance)s%(message)s
logging_debug_format_suffix = {{(pid=%(process)d) %(funcName)s %(pathname)s:%(lineno)d}}

[[post-config|$NOVA_CPU_CONF]]
[DEFAULT]
log_dir = /opt/stack/logs
log_file = nova-compute.log
log_color = False
logging_exception_prefix = ERROR %(name)s %(instance)s
logging_default_format_string = %(levelname)s %(name)s [-] %(instance)s%(message)s
logging_context_format_string = %(levelname)s %(name)s [%(global_request_id)s %(request_id)s %(project_name)s %(user_name)s] %(instance)s%(message)s
logging_debug_format_suffix = {{(pid=%(process)d) %(funcName)s %(pathname)s:%(lineno)d}}
